
server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_management_post_tag_micro_service?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

  application:
    name: POSTING-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

