

server:
  port: 8181

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: CATEGORY-SERVICE
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/categories/**
        - id: POSTING-SERVICE
          uri: lb://POSTING-SERVICE
          predicates:
            - Path=/posts/**
            - Path=/tags/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

