
server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_management_category_service?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

  application:
    name: CATEGORY-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost



